spring:
  application:
    name: Toolbox
    description: A platform for all sorts of tooling.
    version: v1
    developer:
      name: H3AR7B3A7
      mail: steven.d.hondt.sdh@gmail.com
    domain-address: http://localhost:4200/toolbox-ui
  datasource:
    url: jdbc:mysql://localhost:3306/toolbox
    username: root
    password: ${DATABASE_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

---

server:
  servlet:
    context-path: /toolbox-service
  error:
    whitelabel:
      enabled: false

---

management:
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: '*'
    web:
      base-path: /metrics
      exposure:
        include: health, users
  endpoint:
    health:
      enabled: true
      show-details: always
      group:
        db:
          include: db      # /metrics/health/db  : group including only db
          show-components: always
          show-details: always

---

springdoc:
  show-actuator: true
  swagger-ui:
    url: /v3/api-docs.yaml   
    oauth:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
    csrf:
      enabled: true