spring:
  application:
    name: Toolbox
    description: A platform for all sorts of tooling.
    version: v1
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:default;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

---

server:
  servlet:
    context-path: /toolbox-service

---

management:
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: '*'
    web:
      base-path: /metrics
      exposure:
        include: health, users
  endpoint:
    health:
      enabled: true
      show-details: always

---

springdoc:
  show-actuator: true
  swagger-ui:
    oauth:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}