name: "Chromatic Deployment"
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: yarn install --frozen-lockfile
        working-directory: tool-platform-fe
      - name: Build Storybook
        run: yarn run build:storybook
        working-directory: tool-platform-fe
      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: storybook-static
          token: ${{ secrets.GITHUB_TOKEN }}
          workingDir: packages/storybook