name: "Chromatic Deployment"
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: toolbox-fe
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - name: Deploying and testing Storybook
        uses: chromaui/action@v1
        with:
          workingDir: toolbox-fe
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}