name: "Chromatic Deployment"
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: tool-platform-fe
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - uses: chromaui/action@v1
        with:
          workingDir: tool-platform-fe
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}